# Site settings
title: Matthew D. Williams / Designer
email: derrellwilliams@gmail.com
description: "Matthew D. Williams - Graphic/Web Designer based in New York City - Product design portfolio"
baseurl: ""
url: "http://matthewdwilliams.com"
paginate: 10
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: css/sass